import { NextPage } from 'next'
import Head from 'next/head'
import React from 'react'
import { AlphaWarn } from '~/components/dragons'
import { Features } from '~/components/features'

const Miner: NextPage = ({}) => {
  
  return <div>
  <Head>
    <title>My crypto | Software</title>
    <meta name="description" content="Generated by create-t3-app" />
    <link rel="icon" href="/favicon.ico" />
  </Head>
  <div className="flex items-center flex-col">
  <AlphaWarn/>
 <Features/> 
  </div>
</div>
}

export default Miner