import { type NextPage } from "next";
import Head from "next/head";
import { api } from "~/utils/api";
import { AlphaWarn } from "~/components/dragons";


const Wiki: NextPage = () => {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });

  return (
    <div>
      <Head>
        <title>My crypto | Wiki</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex items-center flex-col">
      <AlphaWarn/>
      This is still in developent.
           
      <body>
      
      </body>
      </div>
    </div>
  );
};

export default Wiki;